# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: 周朝苑的个人主页
description: Just a Jekyll theme uesd by zhouchaoyuan.
keywords: Jekyll Theme
url: http://zhouchaoyuan.github.io
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: 周朝苑
    email: chaoyuanzhou@foxmail.com
    imageLink: http://my.chsi.com.cn/archive/viewphoto.action?trnd=86659443279885173839901055376346&type=xj&dtid=y8i7n66ewv593i41
    simpleIntro: 我是周朝苑，一个充满热血的青年！热爱生活！
    detailIntro:
      <p>Jekyll 是一个简洁的、特别针对博客平台的 静态网站 生成器。它使用一个模板目录作为网站布局的基础框架，并在其上运行 Textile 、 Markdown 或 Liquid 标记语言的转换器，最终生成一个完整的静态Web站点，可以被放置在Apache或者你喜欢的其他任何Web服务器上。它同时也是 GitHub Pages 、一个由 GitHub 提供的用于托管项目主页或博客的服务，在后台所运行的引擎。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-weibo
    url: http://weibo.com/chaoyuanzhou
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/zhouchaoyuan
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: huanyueyaoqin
      url: http://huanyueyaoqin.com/
    - text: wangkechun
      url: http://blog.hi-hi.cn/#/
    - text: fengzixu
      url: http://fengzixu.net/
    - text: liuxinglong
      url: http://liuxinglong.github.io/Blog/
    - text: zhouchaoyuan
      url: http://blog.csdn.net/caoguo_app_android
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: zhanxin
